name: Traceability Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Restart PM2 Backend
        run: |
          cd backend
          pm2 delete server --silent
          pm2 start server.js --name server

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Done
        run: echo 'Deployed Successfully!'